@baseUrl = http://localhost:3000
@urlPath=api/gateway/v1/auth

###
POST {{baseUrl}}/{{urlPath}}/register
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "anupam12",
  "email": "anupam+12@pitangent.com",
  "password": "qwerty",
  "country": "Germany",
  "browserName": "chrome",
  "deviceType": "pc",
  "profilePicture": "BGAO;IJPAKEE'PAKPD'L,P"
}

###
POST {{baseUrl}}/{{urlPath}}/login
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "identifier": "anupam12",
  "password": "qwerty",
  "browserName": "chrome",
  "deviceType": "pc"
}

###
GET {{baseUrl}}/{{urlPath}}/current-user
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/refresh-token      
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/change-password      
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/verify-email
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "anupam+12@pitangent.com",
  "token": "334faab6204d2511da5f902b3f3cffa58651949a"
}

###
PUT {{baseUrl}}/{{urlPath}}/verify-otp/:otp      
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/resend-email
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/reset-password/:token
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/logout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/search/gig/0/5/forward?query=beauty&delivery_time=delivery 3 days&minPrice=5&maxPrice=20
Content-Type: application/json
Accept: application/json
withCredentials: true
