@baseUrl = http://localhost:3000
@urlPath=api/gateway/v1/auth

POST {{baseUrl}}/{{urlPath}}/register
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "sunny8",
  "email": "sunny8@test.com",
  "password": "qwerty",
  "country": "Germany",
  "browserName": "test",
  "deviceType": "test",
  "profilePicture": "BGAO;IJPAKEE'PAKPD'L,P"
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "danny",
  "password": "qwerty"
}

###
GET {{baseUrl}}/{{urlPath}}/search/gig/0/5/forward?query=beauty&delivery_time=delivery 3 days&minPrice=5&maxPrice=20
Content-Type: application/json
Accept: application/json
withCredentials: true