@baseUrl = http://localhost:3000
@urlPath=api/gateway/v1/auth

POST {{baseUrl}}/{{urlPath}}/register
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "anupam5",
  "email": "anupam+5@pitangent.com",
  "password": "qwerty",
  "country": "Germany",
  "browserName": "chrome",
  "deviceType": "pc",
  "profilePicture": "BGAO;IJPAKEE'PAKPD'L,P"
}

###
POST {{baseUrl}}/{{urlPath}}/login
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "identifier": "danny",
  "password": "qwerty",
  "browserName": "chrome",
  "deviceType": "pc",
}

###
GET {{baseUrl}}/{{urlPath}}/search/gig/0/5/forward?query=beauty&delivery_time=delivery 3 days&minPrice=5&maxPrice=20
Content-Type: application/json
Accept: application/json
withCredentials: true